# Generated by Django 5.1.7 on 2025-03-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility_services', '0003_alter_servicerequest_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='attached_file',
        ),
    ]
